version: "2"
checks:
  method-complexity:
    config:
      threshold: 7
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-23-0
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  # add stylelint codeclimate
  # stylelint:
  #   enabled: true
  #   channel: "stylelint-14-15-0"
  #   exclude_patterns:
  #   - "**/*.html"
  #   - "**/*.js"
  #   config:
  #     config: .stylelintrc.json
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "spec/"
- "test/"
- "Gemfile.lock"
