# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: bundler-audit
      - id: fasterer
      - id: reek
      - id: rubocop

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        additional_dependencies:
          [
            "stylelint@14.15.0",
            "stylelint-config-recommended@3.0.0",
            "stylelint-config-standard@20.0.0",
            "stylelint-order@4.1.0",
            "stylelint-scss@3.18.0",
          ]
