version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/rails-template
    image: rails-template:latest
    command: bundle exec rails s -u puma -p 3000 -b '0.0.0.0'
    env_file:
      - '.env'
    ports:
      - "80:3000"
    depends_on:
      - mailer
      - redis
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yml
    env_file:
      - '.env'
    volumes:
      - /var/app/current/log/sidekiq/:/rails-template/log
