default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_template_development

test:
  <<: *default
  database: rails_template_test

staging:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
